export const WINDOWS_ENABLE_VIRTUAL_TERMINAL_INPUT = 0x0200;
export const WINDOWS_ENABLE_VIRTUAL_TERMINAL_PROCESSING = 0x0004;
export const WINDOWS_ENABLE_WINDOW_INPUT = 0x0008;
export const WINDOWS_ENABLE_MOUSE_INPUT = 0x0010;
export const WINDOWS_ENABLE_EXTENDED_FLAGS = 0x0080;
