export interface Key {
  readonly type: KeyType;
  readonly runes?: readonly string[];
  readonly alt?: boolean;
  readonly paste?: boolean;
}

export type KeyMsg = Key;

export enum KeyType {
  KeyNull = 0,
  KeyBreak = 3,
  KeyEnter = 13,
  KeyBackspace = 127,
  KeyTab = 9,
  KeyEsc = 27,
  KeyEscape = 27,
  KeyCtrlAt = KeyNull,
  KeyCtrlA = 1,
  KeyCtrlB = 2,
  KeyCtrlC = KeyBreak,
  KeyCtrlD = 4,
  KeyCtrlE = 5,
  KeyCtrlF = 6,
  KeyCtrlG = 7,
  KeyCtrlH = 8,
  KeyCtrlI = KeyTab,
  KeyCtrlJ = 10,
  KeyCtrlK = 11,
  KeyCtrlL = 12,
  KeyCtrlM = KeyEnter,
  KeyCtrlN = 14,
  KeyCtrlO = 15,
  KeyCtrlP = 16,
  KeyCtrlQ = 17,
  KeyCtrlR = 18,
  KeyCtrlS = 19,
  KeyCtrlT = 20,
  KeyCtrlU = 21,
  KeyCtrlV = 22,
  KeyCtrlW = 23,
  KeyCtrlX = 24,
  KeyCtrlY = 25,
  KeyCtrlZ = 26,
  KeyCtrlOpenBracket = KeyEsc,
  KeyCtrlBackslash = 28,
  KeyCtrlCloseBracket = 29,
  KeyCtrlCaret = 30,
  KeyCtrlUnderscore = 31,
  KeyCtrlQuestionMark = KeyBackspace,
  KeyRunes = -1,
  KeyUp = -2,
  KeyDown = -3,
  KeyRight = -4,
  KeyLeft = -5,
  KeyShiftTab = -6,
  KeyHome = -7,
  KeyEnd = -8,
  KeyPgUp = -9,
  KeyPgDown = -10,
  KeyCtrlPgUp = -11,
  KeyCtrlPgDown = -12,
  KeyDelete = -13,
  KeyInsert = -14,
  KeySpace = -15,
  KeyCtrlUp = -16,
  KeyCtrlDown = -17,
  KeyCtrlRight = -18,
  KeyCtrlLeft = -19,
  KeyCtrlHome = -20,
  KeyCtrlEnd = -21,
  KeyShiftUp = -22,
  KeyShiftDown = -23,
  KeyShiftRight = -24,
  KeyShiftLeft = -25,
  KeyShiftHome = -26,
  KeyShiftEnd = -27,
  KeyCtrlShiftUp = -28,
  KeyCtrlShiftDown = -29,
  KeyCtrlShiftLeft = -30,
  KeyCtrlShiftRight = -31,
  KeyCtrlShiftHome = -32,
  KeyCtrlShiftEnd = -33,
  KeyF1 = -34,
  KeyF2 = -35,
  KeyF3 = -36,
  KeyF4 = -37,
  KeyF5 = -38,
  KeyF6 = -39,
  KeyF7 = -40,
  KeyF8 = -41,
  KeyF9 = -42,
  KeyF10 = -43,
  KeyF11 = -44,
  KeyF12 = -45,
  KeyF13 = -46,
  KeyF14 = -47,
  KeyF15 = -48,
  KeyF16 = -49,
  KeyF17 = -50,
  KeyF18 = -51,
  KeyF19 = -52,
  KeyF20 = -53
}

const KEY_NAMES: Partial<Record<KeyType, string>> = {
  [KeyType.KeyNull]: 'ctrl+@',
  [KeyType.KeyCtrlA]: 'ctrl+a',
  [KeyType.KeyCtrlB]: 'ctrl+b',
  [KeyType.KeyCtrlC]: 'ctrl+c',
  [KeyType.KeyCtrlD]: 'ctrl+d',
  [KeyType.KeyCtrlE]: 'ctrl+e',
  [KeyType.KeyCtrlF]: 'ctrl+f',
  [KeyType.KeyCtrlG]: 'ctrl+g',
  [KeyType.KeyCtrlH]: 'ctrl+h',
  [KeyType.KeyCtrlI]: 'tab',
  [KeyType.KeyCtrlJ]: 'ctrl+j',
  [KeyType.KeyCtrlK]: 'ctrl+k',
  [KeyType.KeyCtrlL]: 'ctrl+l',
  [KeyType.KeyCtrlM]: 'enter',
  [KeyType.KeyCtrlN]: 'ctrl+n',
  [KeyType.KeyCtrlO]: 'ctrl+o',
  [KeyType.KeyCtrlP]: 'ctrl+p',
  [KeyType.KeyCtrlQ]: 'ctrl+q',
  [KeyType.KeyCtrlR]: 'ctrl+r',
  [KeyType.KeyCtrlS]: 'ctrl+s',
  [KeyType.KeyCtrlT]: 'ctrl+t',
  [KeyType.KeyCtrlU]: 'ctrl+u',
  [KeyType.KeyCtrlV]: 'ctrl+v',
  [KeyType.KeyCtrlW]: 'ctrl+w',
  [KeyType.KeyCtrlX]: 'ctrl+x',
  [KeyType.KeyCtrlY]: 'ctrl+y',
  [KeyType.KeyCtrlZ]: 'ctrl+z',
  [KeyType.KeyEsc]: 'esc',
  [KeyType.KeyCtrlBackslash]: 'ctrl+\\',
  [KeyType.KeyCtrlCloseBracket]: 'ctrl+]',
  [KeyType.KeyCtrlCaret]: 'ctrl+^',
  [KeyType.KeyCtrlUnderscore]: 'ctrl+_',
  [KeyType.KeyBackspace]: 'backspace',
  [KeyType.KeyRunes]: 'runes',
  [KeyType.KeyUp]: 'up',
  [KeyType.KeyDown]: 'down',
  [KeyType.KeyRight]: 'right',
  [KeyType.KeySpace]: ' ',
  [KeyType.KeyLeft]: 'left',
  [KeyType.KeyShiftTab]: 'shift+tab',
  [KeyType.KeyHome]: 'home',
  [KeyType.KeyEnd]: 'end',
  [KeyType.KeyCtrlHome]: 'ctrl+home',
  [KeyType.KeyCtrlEnd]: 'ctrl+end',
  [KeyType.KeyShiftHome]: 'shift+home',
  [KeyType.KeyShiftEnd]: 'shift+end',
  [KeyType.KeyCtrlShiftHome]: 'ctrl+shift+home',
  [KeyType.KeyCtrlShiftEnd]: 'ctrl+shift+end',
  [KeyType.KeyPgUp]: 'pgup',
  [KeyType.KeyPgDown]: 'pgdown',
  [KeyType.KeyCtrlPgUp]: 'ctrl+pgup',
  [KeyType.KeyCtrlPgDown]: 'ctrl+pgdown',
  [KeyType.KeyDelete]: 'delete',
  [KeyType.KeyInsert]: 'insert',
  [KeyType.KeyCtrlUp]: 'ctrl+up',
  [KeyType.KeyCtrlDown]: 'ctrl+down',
  [KeyType.KeyCtrlRight]: 'ctrl+right',
  [KeyType.KeyCtrlLeft]: 'ctrl+left',
  [KeyType.KeyShiftUp]: 'shift+up',
  [KeyType.KeyShiftDown]: 'shift+down',
  [KeyType.KeyShiftRight]: 'shift+right',
  [KeyType.KeyShiftLeft]: 'shift+left',
  [KeyType.KeyCtrlShiftUp]: 'ctrl+shift+up',
  [KeyType.KeyCtrlShiftDown]: 'ctrl+shift+down',
  [KeyType.KeyCtrlShiftLeft]: 'ctrl+shift+left',
  [KeyType.KeyCtrlShiftRight]: 'ctrl+shift+right',
  [KeyType.KeyF1]: 'f1',
  [KeyType.KeyF2]: 'f2',
  [KeyType.KeyF3]: 'f3',
  [KeyType.KeyF4]: 'f4',
  [KeyType.KeyF5]: 'f5',
  [KeyType.KeyF6]: 'f6',
  [KeyType.KeyF7]: 'f7',
  [KeyType.KeyF8]: 'f8',
  [KeyType.KeyF9]: 'f9',
  [KeyType.KeyF10]: 'f10',
  [KeyType.KeyF11]: 'f11',
  [KeyType.KeyF12]: 'f12',
  [KeyType.KeyF13]: 'f13',
  [KeyType.KeyF14]: 'f14',
  [KeyType.KeyF15]: 'f15',
  [KeyType.KeyF16]: 'f16',
  [KeyType.KeyF17]: 'f17',
  [KeyType.KeyF18]: 'f18',
  [KeyType.KeyF19]: 'f19',
  [KeyType.KeyF20]: 'f20'
};

const joinRunes = (runes?: readonly string[]): string =>
  Array.isArray(runes) ? runes.join('') : '';

export const keyToString = (key: Key): string => {
  const prefix = key.alt ? 'alt+' : '';
  if (key.type === KeyType.KeyRunes) {
    const runeText = joinRunes(key.runes);
    if (key.paste && runeText) {
      return `${prefix}[${runeText}]`;
    }
    return `${prefix}${runeText}`;
  }

  const name = KEY_NAMES[key.type];
  if (typeof name === 'string') {
    return `${prefix}${name}`;
  }
  return '';
};

export const keyTypeToString = (type: KeyType): string => KEY_NAMES[type] ?? '';
