// This file is auto-generated by scripts/generate-key-sequences.mjs.
// Do not edit by hand; update the Go sequences map and re-run the script.
import { KeyType } from '@bubbletea/tea';

export interface SequenceEntry {
  readonly type: KeyType;
  readonly alt?: boolean;
}

export const goSequences: Record<string, SequenceEntry> = {
  // Arrow keys
  "\u001b[A": { type: KeyType.KeyUp },
  "\u001b[B": { type: KeyType.KeyDown },
  "\u001b[C": { type: KeyType.KeyRight },
  "\u001b[D": { type: KeyType.KeyLeft },
  "\u001b[1;2A": { type: KeyType.KeyShiftUp },
  "\u001b[1;2B": { type: KeyType.KeyShiftDown },
  "\u001b[1;2C": { type: KeyType.KeyShiftRight },
  "\u001b[1;2D": { type: KeyType.KeyShiftLeft },
  "\u001b[OA": { type: KeyType.KeyShiftUp }, // DECCKM
  "\u001b[OB": { type: KeyType.KeyShiftDown }, // DECCKM
  "\u001b[OC": { type: KeyType.KeyShiftRight }, // DECCKM
  "\u001b[OD": { type: KeyType.KeyShiftLeft }, // DECCKM
  "\u001b[a": { type: KeyType.KeyShiftUp }, // urxvt
  "\u001b[b": { type: KeyType.KeyShiftDown }, // urxvt
  "\u001b[c": { type: KeyType.KeyShiftRight }, // urxvt
  "\u001b[d": { type: KeyType.KeyShiftLeft }, // urxvt
  "\u001b[1;3A": { type: KeyType.KeyUp, alt: true },
  "\u001b[1;3B": { type: KeyType.KeyDown, alt: true },
  "\u001b[1;3C": { type: KeyType.KeyRight, alt: true },
  "\u001b[1;3D": { type: KeyType.KeyLeft, alt: true },
  "\u001b[1;4A": { type: KeyType.KeyShiftUp, alt: true },
  "\u001b[1;4B": { type: KeyType.KeyShiftDown, alt: true },
  "\u001b[1;4C": { type: KeyType.KeyShiftRight, alt: true },
  "\u001b[1;4D": { type: KeyType.KeyShiftLeft, alt: true },
  "\u001b[1;5A": { type: KeyType.KeyCtrlUp },
  "\u001b[1;5B": { type: KeyType.KeyCtrlDown },
  "\u001b[1;5C": { type: KeyType.KeyCtrlRight },
  "\u001b[1;5D": { type: KeyType.KeyCtrlLeft },
  "\u001b[Oa": { type: KeyType.KeyCtrlUp, alt: true }, // urxvt
  "\u001b[Ob": { type: KeyType.KeyCtrlDown, alt: true }, // urxvt
  "\u001b[Oc": { type: KeyType.KeyCtrlRight, alt: true }, // urxvt
  "\u001b[Od": { type: KeyType.KeyCtrlLeft, alt: true }, // urxvt
  "\u001b[1;6A": { type: KeyType.KeyCtrlShiftUp },
  "\u001b[1;6B": { type: KeyType.KeyCtrlShiftDown },
  "\u001b[1;6C": { type: KeyType.KeyCtrlShiftRight },
  "\u001b[1;6D": { type: KeyType.KeyCtrlShiftLeft },
  "\u001b[1;7A": { type: KeyType.KeyCtrlUp, alt: true },
  "\u001b[1;7B": { type: KeyType.KeyCtrlDown, alt: true },
  "\u001b[1;7C": { type: KeyType.KeyCtrlRight, alt: true },
  "\u001b[1;7D": { type: KeyType.KeyCtrlLeft, alt: true },
  "\u001b[1;8A": { type: KeyType.KeyCtrlShiftUp, alt: true },
  "\u001b[1;8B": { type: KeyType.KeyCtrlShiftDown, alt: true },
  "\u001b[1;8C": { type: KeyType.KeyCtrlShiftRight, alt: true },
  "\u001b[1;8D": { type: KeyType.KeyCtrlShiftLeft, alt: true },
  // Miscellaneous keys
  "\u001b[Z": { type: KeyType.KeyShiftTab },
  "\u001b[2~": { type: KeyType.KeyInsert },
  "\u001b[3;2~": { type: KeyType.KeyInsert, alt: true },
  "\u001b[3~": { type: KeyType.KeyDelete },
  "\u001b[3;3~": { type: KeyType.KeyDelete, alt: true },
  "\u001b[5~": { type: KeyType.KeyPgUp },
  "\u001b[5;3~": { type: KeyType.KeyPgUp, alt: true },
  "\u001b[5;5~": { type: KeyType.KeyCtrlPgUp },
  "\u001b[5^": { type: KeyType.KeyCtrlPgUp }, // urxvt
  "\u001b[5;7~": { type: KeyType.KeyCtrlPgUp, alt: true },
  "\u001b[6~": { type: KeyType.KeyPgDown },
  "\u001b[6;3~": { type: KeyType.KeyPgDown, alt: true },
  "\u001b[6;5~": { type: KeyType.KeyCtrlPgDown },
  "\u001b[6^": { type: KeyType.KeyCtrlPgDown }, // urxvt
  "\u001b[6;7~": { type: KeyType.KeyCtrlPgDown, alt: true },
  "\u001b[1~": { type: KeyType.KeyHome },
  "\u001b[H": { type: KeyType.KeyHome }, // xterm, lxterm
  "\u001b[1;3H": { type: KeyType.KeyHome, alt: true }, // xterm, lxterm
  "\u001b[1;5H": { type: KeyType.KeyCtrlHome }, // xterm, lxterm
  "\u001b[1;7H": { type: KeyType.KeyCtrlHome, alt: true }, // xterm, lxterm
  "\u001b[1;2H": { type: KeyType.KeyShiftHome }, // xterm, lxterm
  "\u001b[1;4H": { type: KeyType.KeyShiftHome, alt: true }, // xterm, lxterm
  "\u001b[1;6H": { type: KeyType.KeyCtrlShiftHome }, // xterm, lxterm
  "\u001b[1;8H": { type: KeyType.KeyCtrlShiftHome, alt: true }, // xterm, lxterm
  "\u001b[4~": { type: KeyType.KeyEnd },
  "\u001b[F": { type: KeyType.KeyEnd }, // xterm, lxterm
  "\u001b[1;3F": { type: KeyType.KeyEnd, alt: true }, // xterm, lxterm
  "\u001b[1;5F": { type: KeyType.KeyCtrlEnd }, // xterm, lxterm
  "\u001b[1;7F": { type: KeyType.KeyCtrlEnd, alt: true }, // xterm, lxterm
  "\u001b[1;2F": { type: KeyType.KeyShiftEnd }, // xterm, lxterm
  "\u001b[1;4F": { type: KeyType.KeyShiftEnd, alt: true }, // xterm, lxterm
  "\u001b[1;6F": { type: KeyType.KeyCtrlShiftEnd }, // xterm, lxterm
  "\u001b[1;8F": { type: KeyType.KeyCtrlShiftEnd, alt: true }, // xterm, lxterm
  "\u001b[7~": { type: KeyType.KeyHome }, // urxvt
  "\u001b[7^": { type: KeyType.KeyCtrlHome }, // urxvt
  "\u001b[7$": { type: KeyType.KeyShiftHome }, // urxvt
  "\u001b[7@": { type: KeyType.KeyCtrlShiftHome }, // urxvt
  "\u001b[8~": { type: KeyType.KeyEnd }, // urxvt
  "\u001b[8^": { type: KeyType.KeyCtrlEnd }, // urxvt
  "\u001b[8$": { type: KeyType.KeyShiftEnd }, // urxvt
  "\u001b[8@": { type: KeyType.KeyCtrlShiftEnd }, // urxvt
  // Function keys, Linux console
  "\u001b[[A": { type: KeyType.KeyF1 }, // linux console
  "\u001b[[B": { type: KeyType.KeyF2 }, // linux console
  "\u001b[[C": { type: KeyType.KeyF3 }, // linux console
  "\u001b[[D": { type: KeyType.KeyF4 }, // linux console
  "\u001b[[E": { type: KeyType.KeyF5 }, // linux console
  // Function keys, X11
  "\u001bOP": { type: KeyType.KeyF1 }, // vt100, xterm
  "\u001bOQ": { type: KeyType.KeyF2 }, // vt100, xterm
  "\u001bOR": { type: KeyType.KeyF3 }, // vt100, xterm
  "\u001bOS": { type: KeyType.KeyF4 }, // vt100, xterm
  "\u001b[1;3P": { type: KeyType.KeyF1, alt: true }, // vt100, xterm
  "\u001b[1;3Q": { type: KeyType.KeyF2, alt: true }, // vt100, xterm
  "\u001b[1;3R": { type: KeyType.KeyF3, alt: true }, // vt100, xterm
  "\u001b[1;3S": { type: KeyType.KeyF4, alt: true }, // vt100, xterm
  "\u001b[11~": { type: KeyType.KeyF1 }, // urxvt
  "\u001b[12~": { type: KeyType.KeyF2 }, // urxvt
  "\u001b[13~": { type: KeyType.KeyF3 }, // urxvt
  "\u001b[14~": { type: KeyType.KeyF4 }, // urxvt
  "\u001b[15~": { type: KeyType.KeyF5 }, // vt100, xterm, also urxvt
  "\u001b[15;3~": { type: KeyType.KeyF5, alt: true }, // vt100, xterm, also urxvt
  "\u001b[17~": { type: KeyType.KeyF6 }, // vt100, xterm, also urxvt
  "\u001b[18~": { type: KeyType.KeyF7 }, // vt100, xterm, also urxvt
  "\u001b[19~": { type: KeyType.KeyF8 }, // vt100, xterm, also urxvt
  "\u001b[20~": { type: KeyType.KeyF9 }, // vt100, xterm, also urxvt
  "\u001b[21~": { type: KeyType.KeyF10 }, // vt100, xterm, also urxvt
  "\u001b[17;3~": { type: KeyType.KeyF6, alt: true }, // vt100, xterm
  "\u001b[18;3~": { type: KeyType.KeyF7, alt: true }, // vt100, xterm
  "\u001b[19;3~": { type: KeyType.KeyF8, alt: true }, // vt100, xterm
  "\u001b[20;3~": { type: KeyType.KeyF9, alt: true }, // vt100, xterm
  "\u001b[21;3~": { type: KeyType.KeyF10, alt: true }, // vt100, xterm
  "\u001b[23~": { type: KeyType.KeyF11 }, // vt100, xterm, also urxvt
  "\u001b[24~": { type: KeyType.KeyF12 }, // vt100, xterm, also urxvt
  "\u001b[23;3~": { type: KeyType.KeyF11, alt: true }, // vt100, xterm
  "\u001b[24;3~": { type: KeyType.KeyF12, alt: true }, // vt100, xterm
  "\u001b[1;2P": { type: KeyType.KeyF13 },
  "\u001b[1;2Q": { type: KeyType.KeyF14 },
  "\u001b[25~": { type: KeyType.KeyF13 }, // vt100, xterm, also urxvt
  "\u001b[26~": { type: KeyType.KeyF14 }, // vt100, xterm, also urxvt
  "\u001b[25;3~": { type: KeyType.KeyF13, alt: true }, // vt100, xterm
  "\u001b[26;3~": { type: KeyType.KeyF14, alt: true }, // vt100, xterm
  "\u001b[1;2R": { type: KeyType.KeyF15 },
  "\u001b[1;2S": { type: KeyType.KeyF16 },
  "\u001b[28~": { type: KeyType.KeyF15 }, // vt100, xterm, also urxvt
  "\u001b[29~": { type: KeyType.KeyF16 }, // vt100, xterm, also urxvt
  "\u001b[28;3~": { type: KeyType.KeyF15, alt: true }, // vt100, xterm
  "\u001b[29;3~": { type: KeyType.KeyF16, alt: true }, // vt100, xterm
  "\u001b[15;2~": { type: KeyType.KeyF17 },
  "\u001b[17;2~": { type: KeyType.KeyF18 },
  "\u001b[18;2~": { type: KeyType.KeyF19 },
  "\u001b[19;2~": { type: KeyType.KeyF20 },
  "\u001b[31~": { type: KeyType.KeyF17 },
  "\u001b[32~": { type: KeyType.KeyF18 },
  "\u001b[33~": { type: KeyType.KeyF19 },
  "\u001b[34~": { type: KeyType.KeyF20 },
  // Powershell sequences.
  "\u001bOA": { type: KeyType.KeyUp, alt: false },
  "\u001bOB": { type: KeyType.KeyDown, alt: false },
  "\u001bOC": { type: KeyType.KeyRight, alt: false },
  "\u001bOD": { type: KeyType.KeyLeft, alt: false },
};

